FROM php:8.2-apache

ADD apache/server.conf /etc/apache2/sites-available/

RUN a2dissite 000-default.conf

RUN a2ensite server.conf

RUN service apache2 restart

WORKDIR /var/www/html/server

COPY json-store-server/ /var/www/html/server

EXPOSE 80